services:
  app:
    image: ${REGISTRY_PREFIX}${PROJECT}:latest
    container_name: $PROJECT
    working_dir: /app
    volumes:
      - voice:/app/src/main/resources/voice
      - tmp_data:/tmp
      - ~/google-credentials.json:/app/google-credentials.json
#    tmpfs: /tmp
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/google-credentials.json
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
      - "$TGBOT_PROXY_PORT:$TGBOT_PROXY_PORT"
    command: >
      sh -c "
      chown -R spring:spring /app/src/main/resources/voice &&
      java
      -Dhttp.proxyHost=$TGBOT_PROXY_HOSTNAME
      -Dhttp.proxyPort=$TGBOT_PROXY_PORT
      -Dhttps.proxyUser=$TGBOT_PROXY_USERNAME
      -Dhttps.proxyPassword=$TGBOT_PROXY_PASSWORD
      org.springframework.boot.loader.launch.JarLauncher
      "
    restart: always
    networks:
      app-network: { }

volumes:
  voice:
  tmp_data:

networks:
  app-network:
