services:
  app:
    image: ${REGISTRY_PREFIX}${PROJECT}:latest
    container_name: $PROJECT
    working_dir: /app
    volumes:
      - ~/voice:/app/src/main/resources/voice
      - ~/google-credentials.json:/app/google-credentials.json
      - tmp_data:/tmp
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/google-credentials.json
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
      - "$TGBOT_PROXY_PORT:$TGBOT_PROXY_PORT"
    mem_limit: 512m
    restart: always
    networks:
      app-network: { }

volumes:
  tmp_data:

networks:
  app-network:
