name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
env:
  ECR_REPOSITORY: ${{ github.event.repository.name }}
  PROJECT: ${{ github.event.repository.name }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
jobs:
  build-and-push-ecr:
    runs-on: ubuntu-22.04
    environment: aws
    env:
      JAVA_VERSION: '21'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get Short SHA
        id: get_short_sha
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          SHA_IMAGE_URI="${{ env.PROJECT }}:${{ env.IMAGE_TAG }}"
          LATEST_IMAGE_URI="${{ env.PROJECT }}:latest"
          docker build -t $SHA_IMAGE_URI -t $LATEST_IMAGE_URI .

      - name: Configure AWS credentials (using OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.PROJECT }}-github-actions-role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActionsSession

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          SHA_IMAGE_URI="${{ env.ECR_REGISTRY }}/${{ env.PROJECT }}:${{ env.IMAGE_TAG }}"
          LATEST_IMAGE_URI="${{ env.ECR_REGISTRY }}/${{ env.PROJECT }}:latest"
          echo $SHA_IMAGE_URI
          # docker build -t $SHA_IMAGE_URI -t $LATEST_IMAGE_URI .
          docker tag ${{ env.PROJECT }}:${{ env.IMAGE_TAG }} $SHA_IMAGE_URI
          docker tag ${{ env.PROJECT }}:latest $LATEST_IMAGE_URI
          docker push $SHA_IMAGE_URI
          docker push $LATEST_IMAGE_URI

      - name: Verify Docker Image on ECR (Optional)
        run: |
          echo ${{ env.IMAGE_TAG }}
          aws ecr describe-images --repository-name $PROJECT --image-ids imageTag=$IMAGE_TAG

  deploy-ec2:
    runs-on: ubuntu-22.04
    environment: aws
    needs: build-and-push-ecr
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials (using OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.PROJECT }}-github-actions-role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActionsSession

      - name: Get EC2 Instance ID
        id: get_ec2_instance
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${{ env.PROJECT }}-ec2" --query "Reservations[*].Instances[*].InstanceId" --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

      - name: Deploy Application to EC2
        run: |
          aws ssm send-command \
              --instance-ids "${{ env.INSTANCE_ID }}" \
              --document-name "AWS-RunShellScript" \
              --comment "Deploy ${{ env.PROJECT }}" \
              --parameters commands=["cd /home/ubuntu/${{ env.PROJECT }}", "./deploy.sh"] \
              --cloud-watch-output-config "CloudWatchLogGroupName=/aws/ssm/${{ env.PROJECT }}-deploy-logs,CloudWatchOutputEnabled=true" \
              --region "${{ env.AWS_REGION }}"
