name: Deploy to EC2

on:
  push:
    branches:
      - main
      - aws

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.TGBOT_GPT_EC2_USER }}@${{ secrets.TGBOT_GPT_EC2_HOST }} << 'EOF'
            mkdir /home/ubuntu/tgbot-gpt
            cd /home/ubuntu/tgbot-gpt
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF