name: Deploy to EC2

on:
  push:
    branches:
      - main
      - aws

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TGBOT_GPT_EC2_SSH_KEY }}" > ~/.ssh/id_ed25519_tgbot_gpt_ec2_deploy_key
          chmod 600 ~/.ssh/id_ed25519_tgbot_gpt_ec2_deploy_key
          ssh-keyscan -H ${{ secrets.TGBOT_GPT_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.TGBOT_GPT_EC2_USER }}@${{ secrets.TGBOT_GPT_EC2_HOST }} << 'EOF'
            mkdir /home/ubuntu/tgbot-gpt
            cd /home/ubuntu/tgbot-gpt
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF